language: generic # undocumented except for https://github.com/travis-ci/docs-travis-ci-com/issues/910
sudo: required

services:
  - docker

script:
  - docker build -t local-test-image .
  - docker run --rm local-test-image java -version 2>&1 | grep GraalVM
