language: generic # undocumented except for https://github.com/travis-ci/docs-travis-ci-com/issues/910
sudo: required

services:
  - docker

script:
  - . ./settings.sh
  - ./bin/build.sh
  - docker image ls
  - ./bin/test-base.sh
  - ./bin/test-native.sh
  - ./bin/test-polyglot.sh

deploy:
  provider: script
  script: ./bin/deploy.sh
  on:
    branch: master
