language: generic # undocumented except for https://github.com/travis-ci/docs-travis-ci-com/issues/910
sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=findepi/graalvm

script:
  - ./bin/build.sh
  - docker image ls
  - docker run --rm local-graalvm:latest java -version 2>&1 | grep GraalVM
  - docker run -i --rm local-graalvm:polyglot graalpython /dev/stdin <<<"print(2**42)" | grep -xF 4398046511104

deploy:
  provider: script
  script: ./bin/deploy.sh
  on:
    branch: master
